### ISSUE TITLE
non functional links shiny seagrass analysis 

### ISSUE THREAD

**Issue by emseabee** [tbep-tech/seagrass-analysis#15]
https://shiny.tbep.org/seagrass-analysis/ this link is throwing me error messages; links are included in various locations

**Comment by fawda123** [comment]
The Shiny server was missing an R package dependency, fixed it here: [98be3620b09e334381e0460412703d3ae3b6e2ae](https://github.com/tbep-tech/tbepdocker/commit/98be3620b09e334381e0460412703d3ae3b6e2ae)

Building the image now, should be up soon.

**Comment by fawda123** [comment]
Should be working now.
