### ISSUE TITLE
Add 1982 data

### ISSUE THREAD

**Issue by fawda123** [tbep-tech/seagrass-analysis#7]
Not sure this has an API link, but it's available here: https://swfwmd.maps.arcgis.com/home/item.html?id=4126c69a0a4c4207949792f3aa4f9eee

**Comment by esherwoo77** [comment]
For the baywide and bay segment estimates for 1950 and 1982, I would use the 'officially' published data found in the FWCC SIMM report, Table 1, here: https://myfwc.com/media/17705/simm3-tampa-bay.pdf .

**Comment by fawda123** [comment]
Done 98a1712612f568b6f987728d803974c54a77e0dd
