### ISSUE TITLE
Bay Segment & MA Boundaries

### ISSUE THREAD

**Issue by esherwoo77** [tbep-tech/seagrass-analysis#8]
If we're trying to develop 'correct' uniform estimates moving forward, then we need to come to agreement on an appropriate partitioning moving forward. Here's the issue at hand:
![image](https://user-images.githubusercontent.com/24903140/132588513-5554955b-fdf3-4ef2-a939-6adbd795a41d.png)

**Comment by fawda123** [comment]
I fixed the management area boundary for area 6, but we still need to decide if we're using SWFWMD areas for calcs or ours.  If the latter, we should add the changes here.
